services:
  web:
    container_name: tuscan-nextjs
    image: tuscan-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules: